apiVersion: v1
kind: PersistentVolume
metadata:
  name: example-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  flexVolume:
    driver: ninefives.online/flexarr
    fsType: "cifs"  # required
    options:
      nasHostname: "nas.example.com"
      nasLocalPath: "/local/path"
      nasNetworkPath: "//nas/path"
    secretRef:
      name: cifs-secret
